version: "3.9"

services:
  redis:
    image: redislabs/redistimeseries:1.10.11
    volumes:
      - "redis-data:/data"
    command: redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so --save "86400 1 21600 20000" # https://github.com/RedisTimeSeries/RedisTimeSeries/blob/master/Dockerfile
  emqx:
    image: emqx:5.5.0
    volumes:
    #  - "./cluster-override.conf:/opt/emqx/data/configs/cluster-override.conf"
    #  - "web-cert:/mnt/web-cert:ro"
    #  - "./certs/zoo.avall.net-fullchain.pem:/opt/emqx/etc/certs/zoo.avall.net-fullchain.pem"
    #  - "./certs/zoo.avall.net-privkey.pem:/opt/emqx/etc/certs/zoo.avall.net-privkey.pem"
    #ports:
    #  - "1883:1883"
    #  - "8883:8883"
    #  - "18083:18083"
    environment:
      - "EMQX_dashboard__default_username=admin"
      - "EMQX_dashboard__default_password=67i5wy6i3apsadgc"
  app:
    image: datahub-app
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
  web:
    image: datahub-web
    ports:
      - "2084:80"
volumes:
  redis-data:
