version: "3.9"

services:
  redis:
    image: redislabs/redistimeseries:1.10.10
    volumes:
      - "redis-data:/data"
    command: redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so --save "86400 1 21600 20000" # https://github.com/RedisTimeSeries/RedisTimeSeries/blob/master/Dockerfile
  app:
    image: datahub-app
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
  web:
    image: datahub-web
    ports:
      - "2084:80"
volumes:
  redis-data:
