version: "3.9"

services:
  redis:
    image: redislabs/redistimeseries:1.10.11
    volumes:
      - "redis-data:/data"
    command: redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so --save "86400 1 21600 20000" # https://github.com/RedisTimeSeries/RedisTimeSeries/blob/master/Dockerfile
  emqx:
    image: emqx:5.5.0
    volumes:
      - "./cluster.hocon:/opt/emqx/data/configs/cluster.hocon"
    #  - "./cluster-override.conf:/opt/emqx/data/configs/cluster-override.conf"
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - "EMQX_dashboard__default_username=admin"
      - "EMQX_dashboard__default_password=67i5wy6i3apsadgc"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 30s
      timeout: 25s
      retries: 5
  app:
    image: datahub-app
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "MQTT_BROKER_URL=emqx"
      - "MQTT_BROKER_URL=1883"
      - "MQTT_USERNAME=mqtt"
      - "MQTT_PASSWORD=mqtt123"
  web:
    image: datahub-web
    ports:
      - "2084:80"
volumes:
  redis-data:
